### ISSUE TITLE
4x compiletime with scala 2.11.1 compared to scala 2.11.0 (Huge use of macro annotations)

### ISSUE THREAD

**Issue by FlorianKirmaier** [scalamacros/paradise#47]
When switching from scala 2.11.0 to scala 2.11.1, I have noticed a huge increase in the compile-time with sbt.
The project makes heavy use of macro-annotations.
The subprojects, which don't use macro-annotations, still have the normal compiletime.
The macro-plugin was added with the following definition in sbt:
addCompilerPlugin("org.scalamacros" % "paradise" % "2.0.0" cross CrossVersion.full),

**Comment by xeno-by** [comment]
Thanks for the report! I'll take a look in the coming hours.

**Comment by xeno-by** [comment]
@FlorianKirmaier Could you test this now with `2.1.0-SNAPSHOT`? Does this help compilation speed?

**Comment by FlorianKirmaier** [comment]
Yes, 2.1.0-SNAPSHOT has the normal compilation speed.
Thank you.

**Comment by xeno-by** [comment]
So what I did yesterday was reverting an innocuously looking commit, and this has unexpectedly seemed to fix the problem. Of course it would be nice to look deeper into it, but unfortunately until ScalaDays I won't have time for that, so here's what I suggest we do. 

I've just reverted my bandaid changes to 2.1.0-SNAPSHOT, so that it stays consistent with other Scala versions (e.g. for 2.10 or 2.11.0) until I get a chance to investigate. I've also published 2.0.1-SNAPSHOT (the version that noone except for you knows that it exists :)) with my yesterday's changes, so that you can use that build until then. Would that work for you?

**Comment by FlorianKirmaier** [comment]
I tested some more, and it looks as i have to take back this bug report.
I still have issues, but its completly different, as i discribed it yesterday.
But you could reproduce something?

It looks as my issues don't depend on the used scala or paradise version.
for some reason "sbt clean publish-local" takes about 50% longer than "sbt compile publish-local".
Now I'm unsure, if a connection to macro annotations exists.

Sorry for the inaccurate bug-report and thanks for the circumstances!

**Comment by xeno-by** [comment]
I heard of paradise causing compilation speed problems, but haven't been able to look into that yet. The last couple of pre-ScalaDays weeks have been very busy. 

So you're saying that the 4x build time degradation is caused by something completely different or paradise also seems to take part in that?

**Comment by FlorianKirmaier** [comment]
There is no 4x degradation .. i missinterpreted some tests.
The only thing that remains, is the slow "publish-local" ... 
which has a big variance in compiletime and is much slower as "compile publish-local"
Dont know if this has to do something with paradise. Probably not.
I close the ticket now, because it causes only confusion.
